name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check linting
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        skip-go-installation: true

    - name: Check format
      run: gofmt -l -d .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...