name: CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: VERSION=$(git tag | tail -1)
    - run: curl https://proxy.golang.org/github.com/halvardssm/go-domeneshop-client/@v/$VERSION.info
